debug: false

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.16.40.89:3306/vote?useUnicode=true&characterEncoding=utf-8
    username: tvfan
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql200:3306/vote?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 5PrzWz34Iglb7KVM
    driver-class-name: com.mysql.jdbc.Driver
